    - name: Create screenshot script
      run: |
        cat << EOF > screenshot.js
        const puppeteer = require('puppeteer');
        const fs = require('fs');
        
        (async () => {
          const browser = await puppeteer.launch({
            headless: 'new',
            args: ['--no-sandbox', '--disable-setuid-sandbox']
          });
          const page = await browser.newPage();
          
          try {
            // Ajustar viewport para captura completa
            await page.setViewport({ width: 1280, height: 800 });
            
            // Navegar a la API de Acestream
            const port = ${{ github.event.inputs.port_base }};
            const url = `http://${process.env.INTERNAL_IP}:${port}/webui/api/service?method=get_version`;
            console.log('Attempting to navigate to:', url);
            await page.goto(url, { waitUntil: 'networkidle0', timeout: 60000 });
            
            // Tomar screenshot
            const screenshotPath = 'acestream_api.png';
            await page.screenshot({ path: screenshotPath, fullPage: true });
            console.log(`Screenshot saved to ${screenshotPath}`);
            
          } catch (error) {
            console.error('Error:', error);
            process.exit(1);
          } finally {
            await browser.close();
          }
        })();
        EOF
