name: Acestream Docker Setup

on:
  workflow_dispatch:
    inputs:
      internal_ip:
        description: "IP interna (deja vacío para autodetectar)"
        required: false
        default: "127.0.0.1"
      port_base:
        description: "Puerto base (6878 por defecto)"
        required: false
        default: "6878"

env:
  IMAGE_NAME: smarquezp/docker-acestream-ubuntu-home:latest
  SERVICE_NAME_BASE: acestream_
  DOCKER_COMPOSE_FILE: docker-compose.yml

jobs:
  setup-acestream:
    runs-on: ubuntu-latest
    outputs:
      container_ip: ${{ steps.ip.outputs.CONTAINER_IP }}
    
    steps:
    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        docker --version
        docker compose version
        
    - name: Set internal IP
      id: ip
      run: |
        if [ "${{ github.event.inputs.internal_ip }}" != "127.0.0.1" ]; then
          echo "INTERNAL_IP=${{ github.event.inputs.internal_ip }}" >> $GITHUB_ENV
          echo "CONTAINER_IP=${{ github.event.inputs.internal_ip }}" >> $GITHUB_OUTPUT
        else
          IP=$(hostname -I | awk '{print $1}')
          echo "INTERNAL_IP=$IP" >> $GITHUB_ENV
          echo "CONTAINER_IP=$IP" >> $GITHUB_OUTPUT
        fi
        echo "Using IP: $INTERNAL_IP"
        
    - name: Create docker-compose.yml
      run: |
        cat << EOF > $DOCKER_COMPOSE_FILE
        version: '3.8'
        services:
          ${SERVICE_NAME_BASE}${{ github.event.inputs.port_base }}:
            image: $IMAGE_NAME
            container_name: ${SERVICE_NAME_BASE}${{ github.event.inputs.port_base }}
            restart: unless-stopped
            network_mode: host
            environment:
              - INTERNAL_IP=$INTERNAL_IP
        EOF
        cat $DOCKER_COMPOSE_FILE
        
    - name: Start Acestream service
      run: |
        docker compose -f $DOCKER_COMPOSE_FILE up -d
        sleep 15
        echo "Acestream running at http://$INTERNAL_IP:${{ github.event.inputs.port_base }}/webui/player/"
        docker ps -a
        docker logs ${SERVICE_NAME_BASE}${{ github.event.inputs.port_base }}
        curl -v http://$INTERNAL_IP:${{ github.event.inputs.port_base }}/webui/api/service?method=get_version || true

  screenshot-api:
    needs: setup-acestream
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Puppeteer
      run: |
        npm install puppeteer
        
    - name: Create screenshot script
      run: |
        cat << 'EOF' > screenshot.js
        const puppeteer = require('puppeteer');
        
        (async () => {
          const browser = await puppeteer.launch({
            headless: 'new',
            args: ['--no-sandbox', '--disable-setuid-sandbox']
          });
          const page = await browser.newPage();
          
          try {
            await page.setViewport({ width: 1280, height: 800 });
            
            const ip = '${{ needs.setup-acestream.outputs.container_ip }}';
            const port = '${{ github.event.inputs.port_base }}';
            const url = `http://${ip}:${port}/webui/api/service?method=get_version`;
            
            console.log(`Attempting to navigate to: ${url}`);
            
            // Configuración más tolerante para entornos CI
            await page.goto(url, {
              waitUntil: 'domcontentloaded',
              timeout: 45000
            });
            
            // Esperar adicional para asegurar carga
            await page.waitForTimeout(5000);
            
            await page.screenshot({
              path: 'acestream_api.png',
              fullPage: true
            });
            
            console.log('Screenshot taken successfully');
            
          } catch (error) {
            console.error('Error during screenshot:', error);
            process.exit(1);
          } finally {
            await browser.close();
          }
        })();
        EOF
        
    - name: Run screenshot script
      timeout-minutes: 2
      run: |
        node screenshot.js || echo "Screenshot failed but continuing workflow"
        
    - name: Upload screenshot artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: acestream-api-screenshot
        path: acestream_api.png
