name: Acestream Screenshot Capture

on:
  workflow_dispatch:
    inputs:
      acestream_id:
        description: 'ID del stream de Acestream (ej: a1b2c3d4e5f6)'
        required: true
      wait_time:
        description: 'Tiempo de espera en segundos (default: 10)'
        required: false
        default: '10'

jobs:
  capture-screenshot:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          vlc \
          xvfb \
          libvlc-dev \
          python3-dev \
          python3-pip \
          curl  # Para subir el artefacto manualmente
        
    - name: Install Acestream Engine
      run: |
        echo "Instalando Acestream..."
        wget -q https://dl.acestream.media/linux/acestream_3.1.49_ubuntu_18.04_x86_64.tar.gz
        tar zxvf acestream_3.1.49_ubuntu_18.04_x86_64.tar.gz
        sudo mv acestream.engine /opt/
        sudo /opt/acestream.engine/start-engine --client-console &
        sleep 10
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mss==6.1.0 python-vlc==3.0.12118
        
    - name: Execute screenshot capture
      env:
        ACESTREAM_ID: ${{ github.event.inputs.acestream_id }}
        WAIT_TIME: ${{ github.event.inputs.wait_time }}
      run: |
        python acestream_screenshot.py
        
        # Comprimir el screenshot para facilitar la subida
        tar czvf screenshot.tar.gz screenshot.png
        
        # Subir manualmente el artefacto via HTTP PUT
        ARTIFACT_URL="${ACTIONS_RUNTIME_URL}_apis/resources/Upload?itemPath=acestream-screenshot%2Fscreenshot.tar.gz"
        curl -X PUT \
          -H "Authorization: Bearer ${ACTIONS_RUNTIME_TOKEN}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @screenshot.tar.gz \
          "$ARTIFACT_URL"
        
        echo "Screenshot subido manualmente como artefacto"
