name: Acestream Screenshot Capture

on:
  workflow_dispatch:
    inputs:
      acestream_id:
        description: 'ID del stream de Acestream'
        required: true
      wait_time:
        description: 'Tiempo de espera en segundos'
        required: false
        default: '20'

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        
    - name: Pull Acestream image
      run: sudo docker pull linuxserver/acestream:latest
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mss requests
        
    - name: Start Acestream container
      env:
        ACESTREAM_ID: ${{ github.event.inputs.acestream_id }}
      run: |
        # Iniciar el contenedor
        sudo docker run -d \
          --name acestream \
          -e PUID=1000 \
          -e PGID=1000 \
          -p 6878:6878 \
          --tmpfs /config \
          linuxserver/acestream:latest
        
        # Esperar a que el servicio esté listo
        python acestream_monitor.py || exit 1
        
        # Reproducir el stream
        curl -X POST \
          "http://localhost:6878/webui/api/service/start_stream?stream_id=$ACESTREAM_ID"
        
    - name: Capture screenshot
      env:
        WAIT_TIME: ${{ github.event.inputs.wait_time }}
      run: |
        # Configurar display virtual
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        
        # Ejecutar captura
        python acestream_screenshot.py
        
    - name: Upload screenshot
      uses: actions/upload-artifact@v3
      with:
        name: acestream-screenshot
        path: screenshot.png
        
    - name: Cleanup
      if: always()
      run: |
        sudo docker stop acestream || true
        sudo docker rm acestream || true
