name: Acestream Screenshot Capture

on:
  workflow_dispatch:
    inputs:
      acestream_id:
        description: 'ID del stream de Acestream'
        required: true
      wait_time:
        description: 'Tiempo de espera en segundos'
        required: false
        default: '10'

jobs:
  capture-screenshot:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          vlc \
          xvfb \
          libvlc-dev \
          python3-dev \
          python3-pip \
          curl \
          wget \
          libpython3.8 \
          libssl1.1 \
          libcurl4 \
          libavcodec58 \
          libavformat58 \
          libswscale5 \
          libx11-6
        
    - name: Install Acestream Engine (versión compatible)
      run: |
        echo "Instalando dependencias específicas de Acestream..."
        sudo apt-get install -y \
          python-software-properties \
          software-properties-common \
          libpython2.7 \
          libssl1.0.0
        
        echo "Descargando Acestream..."
        wget -q https://dl.acestream.media/linux/acestream_3.1.49_ubuntu_18.04_x86_64.tar.gz || \
          { echo "Error al descargar Acestream"; exit 1; }
        
        echo "Extrayendo Acestream..."
        tar zxvf acestream_3.1.49_ubuntu_18.04_x86_64.tar.gz || \
          { echo "Error al extraer Acestream"; exit 1; }
        
        echo "Instalando Acestream..."
        sudo mkdir -p /opt/acestream.engine
        sudo mv acestream.engine/* /opt/acestream.engine/
        sudo chmod +x /opt/acestream.engine/start-engine
        
        echo "Iniciando Acestream Engine..."
        export LD_LIBRARY_PATH=/opt/acestream.engine:$LD_LIBRARY_PATH
        nohup sudo /opt/acestream.engine/start-engine --client-console > /dev/null 2>&1 &
        
        echo "Verificando instalación..."
        sleep 15
        if ! pgrep -f "acestreamengine"; then
          echo "El motor de Acestream no se inició correctamente"
          exit 1
        fi
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mss==6.1.0 python-vlc==3.0.12118
        
    - name: Execute screenshot capture
      env:
        ACESTREAM_ID: ${{ github.event.inputs.acestream_id }}
        WAIT_TIME: ${{ github.event.inputs.wait_time }}
      run: |
        python acestream_screenshot.py
        
        # Comprimir y subir resultados manualmente
        tar czvf results.tar.gz screenshot.png
        curl -X PUT \
          -H "Authorization: Bearer $ACTIONS_RUNTIME_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @results.tar.gz \
          "${ACTIONS_RUNTIME_URL}_apis/resources/Upload?itemPath=acestream-screenshot%2Fresults.tar.gz"
