name: Acestream Docker Setup

on:
  workflow_dispatch:
    inputs:
      port_base:
        description: "Puerto base (6878 por defecto)"
        required: false
        default: "6878"

env:
  IMAGE_NAME: smarquezp/docker-acestream-ubuntu-home:latest
  SERVICE_NAME_BASE: acestream_
  DOCKER_COMPOSE_FILE: docker-compose.yml

jobs:
  setup-acestream:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        docker --version

    - name: Create docker-compose.yml
      run: |
        cat << EOF > $DOCKER_COMPOSE_FILE
        version: '3.8'
        services:
          ${SERVICE_NAME_BASE}${{ github.event.inputs.port_base }}:
            image: $IMAGE_NAME
            container_name: ${SERVICE_NAME_BASE}${{ github.event.inputs.port_base }}
            restart: unless-stopped
            network_mode: host
            ports:
              - "${{ github.event.inputs.port_base }}:${{ github.event.inputs.port_base }}"
        EOF
        cat $DOCKER_COMPOSE_FILE
        
    - name: Start Acestream service
      run: |
        docker compose -f $DOCKER_COMPOSE_FILE up -d
        sleep 30
        echo "Acestream running at http://localhost:${{ github.event.inputs.port_base }}/webui/player/"
        docker ps -a
        docker logs ${SERVICE_NAME_BASE}${{ github.event.inputs.port_base }}

  screenshot-api:
    needs: setup-acestream
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install puppeteer@19.11.1
        sudo apt-get install -y xvfb libgbm-dev
        
    - name: Run screenshot with xvfb
      run: |
        cat << 'EOF' > screenshot.js
        const puppeteer = require('puppeteer');
        
        (async () => {
          const browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox']
          });
          const page = await browser.newPage();
          
          try {
            await page.setViewport({ width: 1280, height: 800 });
            const port = '${{ github.event.inputs.port_base }}';
            const url = `http://localhost:${port}/webui/api/service?method=get_version`;
            
            console.log(`Navigating to: ${url}`);
            await page.goto(url, { waitUntil: 'networkidle2', timeout: 60000 });
            
            await page.waitForTimeout(5000);
            await page.screenshot({ path: 'acestream_api.png', fullPage: true });
            console.log('Screenshot successful');
          } catch (error) {
            console.error('Error:', error);
            process.exit(0);
          } finally {
            await browser.close();
          }
        })();
        EOF
        
        xvfb-run --auto-servernum node screenshot.js || echo "Screenshot failed"
        
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: acestream-results
        path: |
          acestream_api.png
          screenshot.js
