name: Acestream Screenshot Capture

on:
  workflow_dispatch:
    inputs:
      acestream_id:
        description: 'ID del stream de Acestream (ej: a1b2c3d4e5f6)'
        required: true
      wait_time:
        description: 'Tiempo de espera en segundos (default: 10)'
        required: false
        default: '10'

jobs:
  capture-screenshot:
    runs-on: ubuntu-20.04  # Usamos una versión específica compatible
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Versión más antigua
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          vlc \
          xvfb \
          libvlc-dev \
          python3-dev \
          python3-pip
        
    - name: Install Acestream Engine
      run: |
        echo "Instalando Acestream..."
        wget -q https://dl.acestream.media/linux/acestream_3.1.49_ubuntu_20.04_x86_64.tar.gz
        tar zxvf acestream_3.1.49_ubuntu_20.04_x86_64.tar.gz
        sudo mv acestream.engine /opt/
        sudo /opt/acestream.engine/start-engine --client-console &
        sleep 10  # Esperar a que el engine inicie completamente
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mss python-vlc
        
    - name: Execute screenshot capture
      env:
        ACESTREAM_ID: ${{ github.event.inputs.acestream_id }}
        WAIT_TIME: ${{ github.event.inputs.wait_time }}
        OUTPUT_FILE: 'screenshot.png'
      run: |
        python acestream_screenshot.py
        
    - name: Upload screenshot
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: acestream-screenshot
        path: |
          screenshot.png
          *.log
        retention-days: 1
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: error-logs
        path: |
          /tmp/*.log
          /var/log/*
        retention-days: 1
