name: Acestream Docker Setup (No Clone Needed)

on:
  workflow_dispatch:
    inputs:
      internal_ip:
        description: "IP interna (deja vacío para autodetectar)"
        required: false
        default: "127.0.0.1"
      port_base:
        description: "Puerto base (6878 por defecto)"
        required: false
        default: "6878"

env:
  IMAGE_NAME: smarquezp/docker-acestream-ubuntu-home:latest
  SERVICE_NAME_BASE: acestream_
  DOCKER_COMPOSE_FILE: docker-compose.yml

jobs:
  setup-acestream:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Docker and dependencies
      run: |
        # Limpiar instalaciones previas de Docker (opcional pero recomendado)
        sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
        
        # Instalar dependencias base
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        
        # Añadir repositorio oficial de Docker
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        
        # Instalar Docker Engine (esto resolverá los conflictos de containerd)
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
        
        # Verificar instalación
        sudo docker --version
        sudo docker-compose --version
             
    - name: Set internal IP
      id: ip
      run: |
        if [ "${{ github.event.inputs.internal_ip }}" != "127.0.0.1" ]; then
          echo "INTERNAL_IP=${{ github.event.inputs.internal_ip }}" >> $GITHUB_ENV
        else
          IP=$(hostname -I | awk '{print $1}')
          if [ -z "$IP" ]; then
            IP="127.0.0.1"
          fi
          echo "INTERNAL_IP=$IP" >> $GITHUB_ENV
          echo "Using detected IP: $IP"
        fi
        
    - name: Create docker-compose.yml dynamically
      run: |
        cat << EOF > $DOCKER_COMPOSE_FILE
        version: '3.8'
        services:
          $SERVICE_NAME:
            image: $IMAGE_NAME
            container_name: $SERVICE_NAME
            restart: unless-stopped
            ports:
              - "$PORT:$PORT"
            environment:
              - INTERNAL_IP=$INTERNAL_IP
        EOF
        echo "Generated docker-compose.yml:"
        cat $DOCKER_COMPOSE_FILE
        
    - name: Start Acestream service
      run: |
        docker-compose -f $DOCKER_COMPOSE_FILE up -d
        echo "Acestream running at http://$INTERNAL_IP:$PORT/webui/player/"
