name: Capture Screenshot

on:
  workflow_dispatch:

jobs:
  capture_screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get remove -y docker docker-engine docker.io containerd runc
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce

    - name: Pull Acestream image
      run: sudo docker pull vstavrinov/acestream-engine

    - name: Run Acestream container
      run: |
        sudo docker run -d --name acestream -p 6878:6878 vstavrinov/acestream-engine
        sleep 10  # Espera 10 segundos para que el stream se inicie

    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3

    - name: Run capture script
      run: python3 scripts/capture_screenshot.py

    - name: Capture screenshot
      run: |
       mpeg -i http://127.0.0.1:6878/ace/getstream -vframes 1 ace_kanalak/screenshot.png

    - name: Check Acestream logs
      run: sudo docker logs acestream

    - name: Stop Acestream container
      run: sudo docker stop acestream
