name: Acestream Screenshot

on:
  workflow_dispatch:

jobs:
  acestream-screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone Acestream Docker project
      run: git clone https://github.com/sergiomarquezdev/acestream-docker-home.git

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Acestream Docker image
      run: |
        cd acestream-docker-home
        docker build --no-cache -t docker-acestream .

    - name: Start Acestream container
      id: start_acestream
      run: |
        docker run --name acestream -d -p 6878:6878 -e INTERNAL_IP=127.0.0.1 --restart unless-stopped docker-acestream
        sleep 30  # Esperar a que el stream esté disponible
        echo "CONTAINER_ID=$(docker ps -q --filter name=acestream)" >> $GITHUB_ENV

    - name: Check container health status
      run: docker inspect --format='{{json .State.Health}}' ${{ env.CONTAINER_ID }}

    - name: Take screenshot with FFmpeg
      run: |
        docker run --rm -v ${{ github.workspace }}:/screenshots jrottenberg/ffmpeg \
        -i http://127.0.0.1:6878/webui/player/1205151f6fa5d95c0eeb543cbce43ccfa6a1b216 \
        -vframes 1 /screenshots/screenshot.png

    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      with:
        name: screenshot
        path: screenshot.png
