name: Capture Screenshot

on:
  workflow_dispatch:

jobs:
  capture_screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce

    - name: Pull Acestream image
      run: sudo docker pull vstavrinov/acestream-engine

    - name: Run Acestream container
      run: |
        sudo docker run -d \
          --name acestream \
          -p 6878:6878 \
          vstavrinov/acestream-engine
        sleep 30  # Espera amplia para inicialización

    - name: Start stream playback
      run: |
        sudo docker exec -d acestream \
          /acestream/start-engine \
          --client-console \
          --play-and-exit \
          acestream://1205151f6fa5d95c0eeb543cbce43ccfa6a1b216
        sleep 20  # Espera para que el stream esté disponible

    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3

    - name: Create output directory
      run: mkdir -p ace_kanalak

    - name: Capture screenshot
      run: |
        ffmpeg -y \
          -i "http://127.0.0.1:6878/ace/getstream?id=1205151f6fa5d95c0eeb543cbce43ccfa6a1b216" \
          -vframes 1 \
          -f image2 \
          ace_kanalak/screenshot.png

    - name: Verify screenshot
      run: |
        ls -la ace_kanalak/
        file ace_kanalak/screenshot.png

    - name: Check Acestream logs
      if: always()
      run: sudo docker logs acestream

    - name: Cleanup
      if: always()
      run: |
        sudo docker stop acestream || true
        sudo docker rm acestream || true
