name: Verificar Stream Acestream

on:
  workflow_dispatch:

jobs:
  verify-acestream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y curl ffmpeg docker.io

    - name: Iniciar contenedor Acestream
      id: start_acestream
      run: |
        # Primero intentamos con la imagen oficial de Acestream
        if ! docker run --name acestream -d \
          -p 6878:6878 \
          -p 8621:8621 \
          -e EXTERNAL_PORT=8621 \
          acestream/acestream; then
          
          echo "Falló imagen oficial, probando alternativa..."
          docker pull sergiomarquez/acestream-docker:latest
          docker run --name acestream -d \
            -p 6878:6878 \
            -p 8621:8621 \
            sergiomarquez/acestream-docker
        fi
        
        echo "CONTAINER_ID=$(docker ps -q --filter name=acestream)" >> $GITHUB_ENV
        sleep 30

    - name: Verificar logs del contenedor
      run: |
        docker logs ${{ env.CONTAINER_ID }} --tail 100
        docker inspect ${{ env.CONTAINER_ID }}

    - name: Verificar conexión
      run: |
        # Espera con reintentos inteligentes
        for i in {1..10}; do
          if curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:6878/webui/ | grep -q "200"; then
            echo "WebUI accesible"
            exit 0
          fi
          echo "Intento $i/10 - Esperando servicio..."
          sleep 10
          docker logs ${{ env.CONTAINER_ID }} --tail 20
        done
        echo "Error: WebUI no accesible después de 10 intentos"
        exit 1

    - name: Verificar stream
      if: success()
      run: |
        STREAM_ID="6538b79ce0da657d8455d1da6a5f342398899a0e"
        timeout 30 ffprobe -v error -show_entries format=duration \
          "http://127.0.0.1:6878/webui/player/$STREAM_ID" && \
          echo "Stream activo" || \
          echo "Error analizando stream"

    - name: Limpieza
      if: always()
      run: |
        docker stop acestream || true
        docker rm acestream || true
