name: Verificar Stream Acestream

on:
  workflow_dispatch:

jobs:
  verify-acestream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y netcat-openbsd curl ffmpeg

    - name: Clonar proyecto Acestream Docker
      run: git clone https://github.com/sergiomarquezdev/acestream-docker-home.git

    - name: Configurar Docker
      uses: docker/setup-buildx-action@v1

    - name: Construir imagen Docker
      run: |
        cd acestream-docker-home
        docker build --no-cache -t docker-acestream .

    - name: Iniciar contenedor Acestream
      id: start_acestream
      run: |
        docker run --name docker-acestream -d -p 6878:6878 -e INTERNAL_IP=127.0.0.1 --restart unless-stopped docker-acestream
        docker compose up -d
        sleep 15
        docker compose pull && docker compose up -d
        sleep 15
        docker inspect --format='{{json .State.Health}}' docker-acestream

    - name: Verificar puerto
      run: |
        if nc -zv 127.0.0.1 6878; then
          echo "El puerto 6878 está abierto y escuchando."
        else
          echo "El puerto 6878 no está disponible."
        fi

    - name: Verificar conexión HTTP
      run: |
        if curl -s "http://127.0.0.1:6878/webui/" | grep -q "AceStream"; then
          echo "Conexión HTTP exitosa."
        else
          echo "Error en la conexión HTTP."
        fi

    - name: Verificar stream específico
      run: |
        STREAM_ID="6538b79ce0da657d8455d1da6a5f342398899a0e"
        echo "Verificando stream ID: $STREAM_ID"
        timeout 30 ffprobe -v error -show_entries format=duration \
          -of default=noprint_wrappers=1:nokey=1 \
          "http://127.0.0.1:6878/webui/player/$STREAM_ID" && \
          echo "Stream verificado correctamente" || \
          echo "No se pudo analizar el stream"

    - name: Limpieza
      if: always()
      run: |
        docker stop docker-acestream || true
        docker rm docker-acestream || true
