name: Verificar Stream Acestream

on:
  workflow_dispatch:

jobs:
  verify-acestream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y curl ffmpeg

    - name: Iniciar contenedor Acestream (versión alternativa)
      id: start_acestream
      run: |
        docker run --name acestream -d \
          -p 6878:6878 \
          -p 8621:8621 \
          -e EXTERNAL_PORT=8621 \
          -e GLOBAL_ACCESS=1 \
          --restart unless-stopped \
          ghcr.io/linuxserver/acestream
        echo "CONTAINER_ID=$(docker ps -q --filter name=acestream)" >> $GITHUB_ENV
        sleep 30  # Espera más tiempo para inicialización

    - name: Verificar logs del contenedor
      run: |
        docker logs ${{ env.CONTAINER_ID }} --tail 100
        docker exec ${{ env.CONTAINER_ID }} ps aux

    - name: Verificar servicios internos
      run: |
        # Verificar procesos internos
        docker exec ${{ env.CONTAINER_ID }} netstat -tulnp || true
        docker exec ${{ env.CONTAINER_ID }} curl -v http://localhost:6878/webui/ || true

    - name: Verificar acceso externo
      run: |
        # Esperar hasta que responda (máx 2 minutos)
        timeout 120 bash -c 'until curl -s --retry 5 --retry-delay 10 --connect-timeout 5 http://127.0.0.1:6878/webui/; do
          echo "Esperando que webui esté disponible..."
          docker logs ${{ env.CONTAINER_ID }} --tail 20
          sleep 10
        done'
        
        # Verificar API
        curl -v "http://127.0.0.1:6878/webui/api/status"

    - name: Limpieza
      if: always()
      run: |
        docker stop acestream || true
        docker rm acestream || true
