name: Verificar Stream Acestream

on:
  workflow_dispatch:

jobs:
  verify-acestream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configurar Docker oficial (sin conflictos)
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Instalar dependencias básicas
      run: |
        sudo apt-get update
        sudo apt-get install -y curl ffmpeg

    - name: Iniciar contenedor Acestream
      id: start_acestream
      run: |
        # Usamos imagen oficial con versión específica para evitar problemas
        docker run --name acestream -d \
          --network host \
          -e EXTERNAL_IP=127.0.0.1 \
          acestream/acestream:3.1.49
        
        echo "CONTAINER_ID=$(docker ps -q --filter name=acestream)" >> $GITHUB_ENV
        sleep 30

    - name: Verificar estado del contenedor
      run: |
        docker ps -a
        docker logs ${{ env.CONTAINER_ID }} --tail 100

    - name: Verificar conexión al servicio
      run: |
        # Espera con chequeo activo
        for i in {1..12}; do
          if curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:6878/webui/ | grep -q "200"; then
            echo "✅ Servicio Acestream disponible"
            exit 0
          fi
          echo "⌛ Intento $i/12 - Esperando servicio..."
          docker logs ${{ env.CONTAINER_ID }} --tail 10
          sleep 10
        done
        echo "❌ Servicio no disponible después de 2 minutos"
        exit 1

    - name: Verificar stream específico
      if: success()
      run: |
        STREAM_ID="6538b79ce0da657d8455d1da6a5f342398899a0e"
        echo "🔍 Verificando stream ID: $STREAM_ID"
        
        # Método alternativo usando timeout y curl
        if timeout 30 curl -v "http://127.0.0.1:6878/webui/player/$STREAM_ID" | grep -q "acestream://"; then
          echo "✅ Stream detectado"
        else
          echo "❌ No se pudo acceder al stream"
          docker logs ${{ env.CONTAINER_ID }} --tail 50
          exit 1
        fi

    - name: Limpieza
      if: always()
      run: |
        docker stop acestream || true
        docker rm acestream || true
